import type { Transaction } from "@/types";

// Reference "now" for this dataset: Aug 24, 2026, 12:00 UTC
const ts = (offsetMinutesAgo: number) =>
  new Date(new Date("2026-08-24T12:00:00Z").getTime() - offsetMinutesAgo * 60_000).toISOString();

export const transactions: Transaction[] = [
  { id: "TXN-8392", customerId: "CUS-104", amount: 24999, currency: "INR", provider: "Stripe", paymentMethod: "Credit Card", status: "FAILED", risk: "NORMAL", authorizationStatus: "DECLINED", providerResponse: "Card declined: insufficient funds", errorCode: "51", incidentId: "INC-1024", ipAddress: "103.21.45.12", createdAt: ts(89) },
  { id: "TXN-8391", customerId: "CUS-108", amount: 89999, currency: "INR", provider: "Razorpay", paymentMethod: "Credit Card", status: "FAILED", risk: "HIGH", authorizationStatus: "DECLINED", providerResponse: "Risk engine flagged transaction", errorCode: "RISK_BLOCK", incidentId: "INC-1023", ipAddress: "45.132.88.201", createdAt: ts(134) },
  { id: "TXN-8387", customerId: "CUS-111", amount: 12500, currency: "INR", provider: "PayU", paymentMethod: "Net Banking", status: "FAILED", risk: "NORMAL", authorizationStatus: "PENDING", providerResponse: "Gateway timeout after 30s", errorCode: "TIMEOUT", incidentId: "INC-1022", ipAddress: "117.98.12.4", createdAt: ts(212) },
  { id: "TXN-8382", customerId: "CUS-103", amount: 5499, currency: "INR", provider: "Stripe", paymentMethod: "UPI", status: "REFUNDED", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Duplicate charge detected and reversed", errorCode: null, incidentId: "INC-1021", ipAddress: "49.204.11.90", createdAt: ts(340) },
  { id: "TXN-8380", customerId: "CUS-113", amount: 31200, currency: "INR", provider: "Adyen", paymentMethod: "Credit Card", status: "FAILED", risk: "HIGH", authorizationStatus: "DECLINED", providerResponse: "Multiple velocity checks failed", errorCode: "VELOCITY", incidentId: "INC-1020", ipAddress: "88.212.4.19", createdAt: ts(360) },
  { id: "TXN-8379", customerId: "CUS-101", amount: 2999, currency: "INR", provider: "Stripe", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "103.21.45.12", createdAt: ts(365) },
  { id: "TXN-8378", customerId: "CUS-106", amount: 8900, currency: "INR", provider: "Razorpay", paymentMethod: "Debit Card", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "27.7.100.3", createdAt: ts(400) },
  { id: "TXN-8377", customerId: "CUS-107", amount: 1540, currency: "INR", provider: "PayPal", paymentMethod: "Wallet", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "182.75.4.201", createdAt: ts(410) },
  { id: "TXN-8376", customerId: "CUS-102", amount: 1899, currency: "INR", provider: "Stripe", paymentMethod: "Credit Card", status: "PENDING", risk: "NORMAL", authorizationStatus: "PENDING", providerResponse: "Awaiting bank confirmation", errorCode: null, incidentId: null, ipAddress: "115.99.4.8", createdAt: ts(15) },
  { id: "TXN-8375", customerId: "CUS-109", amount: 3990, currency: "INR", provider: "Razorpay", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "49.36.88.14", createdAt: ts(430) },
  { id: "TXN-8374", customerId: "CUS-108", amount: 15000, currency: "INR", provider: "Razorpay", paymentMethod: "Credit Card", status: "FAILED", risk: "HIGH", authorizationStatus: "DECLINED", providerResponse: "Insufficient funds", errorCode: "51", incidentId: "INC-1019", ipAddress: "45.132.88.201", createdAt: ts(140) },
  { id: "TXN-8373", customerId: "CUS-108", amount: 15000, currency: "INR", provider: "Razorpay", paymentMethod: "Credit Card", status: "FAILED", risk: "HIGH", authorizationStatus: "DECLINED", providerResponse: "Insufficient funds", errorCode: "51", incidentId: "INC-1018", ipAddress: "192.42.116.7", createdAt: ts(145) },
  { id: "TXN-8372", customerId: "CUS-108", amount: 15000, currency: "INR", provider: "Razorpay", paymentMethod: "Debit Card", status: "FAILED", risk: "HIGH", authorizationStatus: "DECLINED", providerResponse: "Card declined by issuer", errorCode: "05", incidentId: "INC-1017", ipAddress: "45.132.88.201", createdAt: ts(150) },
  { id: "TXN-8371", customerId: "CUS-110", amount: 2200, currency: "INR", provider: "Stripe", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "223.176.4.90", createdAt: ts(460) },
  { id: "TXN-8370", customerId: "CUS-105", amount: 27600, currency: "INR", provider: "Adyen", paymentMethod: "Credit Card", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "106.51.20.9", createdAt: ts(480) },
  { id: "TXN-8369", customerId: "CUS-114", amount: 3100, currency: "INR", provider: "Stripe", paymentMethod: "Wallet", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "117.239.4.5", createdAt: ts(500) },
  { id: "TXN-8368", customerId: "CUS-112", amount: 990, currency: "INR", provider: "PayU", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "49.15.201.6", createdAt: ts(520) },
  { id: "TXN-8367", customerId: "CUS-115", amount: 64200, currency: "INR", provider: "Stripe", paymentMethod: "Credit Card", status: "SUCCESS", risk: "ELEVATED", authorizationStatus: "AUTHORIZED", providerResponse: "Approved after manual review", errorCode: null, incidentId: null, ipAddress: "182.156.4.201", createdAt: ts(540) },
  { id: "TXN-8366", customerId: "CUS-116", amount: 1980, currency: "INR", provider: "PayPal", paymentMethod: "Wallet", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "223.185.4.55", createdAt: ts(560) },
  { id: "TXN-8365", customerId: "CUS-104", amount: 41200, currency: "INR", provider: "Stripe", paymentMethod: "Credit Card", status: "FAILED", risk: "ELEVATED", authorizationStatus: "DECLINED", providerResponse: "Card declined: insufficient funds", errorCode: "51", incidentId: "INC-1016", ipAddress: "103.21.45.12", createdAt: ts(600) },
  { id: "TXN-8364", customerId: "CUS-113", amount: 28900, currency: "INR", provider: "Adyen", paymentMethod: "Credit Card", status: "PENDING", risk: "ELEVATED", authorizationStatus: "PENDING", providerResponse: "3DS verification in progress", errorCode: null, incidentId: null, ipAddress: "88.212.4.19", createdAt: ts(30) },
  { id: "TXN-8363", customerId: "CUS-103", amount: 5499, currency: "INR", provider: "Stripe", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "49.204.11.90", createdAt: ts(620) },
  { id: "TXN-8362", customerId: "CUS-106", amount: 8900, currency: "INR", provider: "Razorpay", paymentMethod: "Debit Card", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "27.7.100.3", createdAt: ts(650) },
  { id: "TXN-8361", customerId: "CUS-107", amount: 1540, currency: "INR", provider: "PayU", paymentMethod: "UPI", status: "FAILED", risk: "NORMAL", authorizationStatus: "DECLINED", providerResponse: "Provider timeout", errorCode: "TIMEOUT", incidentId: "INC-1015", ipAddress: "182.75.4.201", createdAt: ts(700) },
  { id: "TXN-8360", customerId: "CUS-109", amount: 3990, currency: "INR", provider: "Razorpay", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "49.36.88.14", createdAt: ts(720) },
  { id: "TXN-8359", customerId: "CUS-102", amount: 1899, currency: "INR", provider: "Stripe", paymentMethod: "Credit Card", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "115.99.4.8", createdAt: ts(760) },
  { id: "TXN-8358", customerId: "CUS-101", amount: 2999, currency: "INR", provider: "Stripe", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "103.21.45.12", createdAt: ts(800) },
  { id: "TXN-8357", customerId: "CUS-111", amount: 12500, currency: "INR", provider: "PayU", paymentMethod: "Net Banking", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "117.98.12.4", createdAt: ts(840) },
  { id: "TXN-8356", customerId: "CUS-114", amount: 3100, currency: "INR", provider: "Stripe", paymentMethod: "Wallet", status: "REFUNDED", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Customer requested refund", errorCode: null, incidentId: null, ipAddress: "117.239.4.5", createdAt: ts(900) },
  { id: "TXN-8355", customerId: "CUS-105", amount: 2760, currency: "INR", provider: "Razorpay", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "106.51.20.9", createdAt: ts(950) },
  { id: "TXN-8354", customerId: "CUS-110", amount: 2200, currency: "INR", provider: "Stripe", paymentMethod: "UPI", status: "FAILED", risk: "NORMAL", authorizationStatus: "DECLINED", providerResponse: "Card expired", errorCode: "54", incidentId: "INC-1014", ipAddress: "223.176.4.90", createdAt: ts(1000) },
  { id: "TXN-8353", customerId: "CUS-116", amount: 1980, currency: "INR", provider: "PayPal", paymentMethod: "Wallet", status: "FAILED", risk: "NORMAL", authorizationStatus: "DECLINED", providerResponse: "Card declined by issuer", errorCode: "05", incidentId: "INC-1013", ipAddress: "223.185.4.55", createdAt: ts(1040) },
  { id: "TXN-8352", customerId: "CUS-112", amount: 990, currency: "INR", provider: "PayU", paymentMethod: "UPI", status: "SUCCESS", risk: "NORMAL", authorizationStatus: "AUTHORIZED", providerResponse: "Approved", errorCode: null, incidentId: null, ipAddress: "49.15.201.6", createdAt: ts(1080) },
];

export function getTransactionById(id: string): Transaction | undefined {
  return transactions.find((t) => t.id === id);
}
